//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountInfo
    {
        public tblAccountInfo()
        {
            this.tblBudgets = new HashSet<tblBudget>();
            this.tblDeposits = new HashSet<tblDeposit>();
            this.tblExpenses = new HashSet<tblExpens>();
            this.tblSavings = new HashSet<tblSaving>();
            this.tblAccountSummaries = new HashSet<tblAccountSummary>();
            this.tblTransactions = new HashSet<tblTransaction>();
            this.tblWithdraws = new HashSet<tblWithdraw>();
        }
    
        public int UserID { get; set; }
        public string UserLogIn { get; set; }
        public string UserPassword { get; set; }
        public string UserFName { get; set; }
        public string UserLName { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<tblBudget> tblBudgets { get; set; }
        public virtual ICollection<tblDeposit> tblDeposits { get; set; }
        public virtual ICollection<tblExpens> tblExpenses { get; set; }
        public virtual ICollection<tblSaving> tblSavings { get; set; }
        public virtual ICollection<tblAccountSummary> tblAccountSummaries { get; set; }
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
        public virtual ICollection<tblWithdraw> tblWithdraws { get; set; }
    }
}
