//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourMoney.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountSummary
    {
        public int SummaryID { get; set; }
        public int UserID { get; set; }
        public int DepositID { get; set; }
        public int WithdrawID { get; set; }
        public int BudgetID { get; set; }
        public int SavingsID { get; set; }
        public int TransactionID { get; set; }
        public int ExpenseID { get; set; }
        public Nullable<decimal> Projected { get; set; }
        public Nullable<decimal> Actual { get; set; }
        public Nullable<decimal> Difference { get; set; }
    
        public virtual tblAccountInfo tblAccountInfo { get; set; }
        public virtual tblBudget tblBudget { get; set; }
        public virtual tblDeposit tblDeposit { get; set; }
        public virtual tblExpens tblExpens { get; set; }
        public virtual tblSaving tblSaving { get; set; }
        public virtual tblTransaction tblTransaction { get; set; }
        public virtual tblWithdraw tblWithdraw { get; set; }
    }
}
